DROP TABLE IF EXISTS public.project;

CREATE TABLE IF NOT EXISTS public.project
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    postcode integer NOT NULL,
    expected_no_of_hours integer,
    due_date_time timestamp without time zone NOT NULL,
    summary character varying(255) COLLATE pg_catalog."default" NOT NULL,
    budget bigint,
    status character varying(255) COLLATE pg_catalog."default",
    assigned_bid_id bigint,
    created_by character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone,
    last_modified_by character varying(50) COLLATE pg_catalog."default",
    last_modified_date timestamp without time zone,
    CONSTRAINT project_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.project
    OWNER to smartbiddinguser;



DROP TABLE IF EXISTS public.project_bid;

CREATE TABLE IF NOT EXISTS public.project_bid
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bid_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bid_amount double precision NOT NULL,
    comments character varying(255) COLLATE pg_catalog."default",
    bid_status character varying(255) COLLATE pg_catalog."default",
    project_id bigint,
    created_by character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone,
    last_modified_by character varying(50) COLLATE pg_catalog."default",
    last_modified_date timestamp without time zone,
    CONSTRAINT project_bid_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_bid__project_id FOREIGN KEY (project_id)
    REFERENCES public.project (id) MATCH SIMPLE
                           ON UPDATE NO ACTION
                           ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.project_bid
    OWNER to smartbiddinguser;

ALTER TABLE project_bid DROP CONSTRAINT fk_project_bid__project_id;